# This workflow will publish any new version of Lussac on Test PyPI.

name: Release to Test PyPI

on:
  pull_request:
    branches:
      - main
      - v2.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
        pip install -e .[dev]
        cd ..
        git clone https://github.com/SpikeInterface/spikeinterface.git
        cd spikeinterface
        pip uninstall -y spikeinterface
        pip install -e .
        cd ../lussac
        python -m build --sdist --wheel --outdir dist/
    - name: Cache datasets
      id: cache-datasets
      uses: actions/cache@v3
      with:
        path: tests/datasets
        key: ${{ runner.os }}-datasets
    - name: Test with pytest
      run: |
        pytest
    - name: Publish on Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
