# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lussac unit tests (Windows)

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        pip install git+https://github.com/SpikeInterface/spikeinterface.git
    - name: Cache datasets
      id: cache-datasets
      uses: actions/cache@v3
      with:
        path: tests/datasets
        key: ${{ runner.os }}-datasets
    - name: Test with pytest
      run: |
        pytest
